export const courses = [
  { id: 1, name: "Administração", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 2,
    name: "Administração - EaD",
    degree: "Bacharelado",
    mode: "Educação a Distância",
  },
  {
    id: 3,
    name: "Análise e Desenvolvimento de Sistemas - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 4,
    name: "Arquitetura e Urbanismo",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  { id: 5, name: "Biomedicina", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 6,
    name: "Ciência da Computação",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 7,
    name: "Ciência de Dados - EAD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 8,
    name: "Ciências Biológicas",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 9,
    name: "Ciências Contábeis",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 10,
    name: "Ciências Contábeis - EaD",
    degree: "Bacharelado",
    mode: "Educação a Distância",
  },
  {
    id: 11,
    name: "Comércio Exterior",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 12,
    name: "Comércio Exterior - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 13,
    name: "Design",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 14,
    name: "Design com Linha de Formação em Design de Jogos e Entretenimento Digital",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 15,
    name: "Design de Games",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 16,
    name: "Design de Interiores",
    degree: "Tecnólogo",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 17,
    name: "Design de Interiores - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 18,
    name: "Design de Moda",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 19,
    name: "Design Gráfico - Bacharelado",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 20,
    name: "Design Gráfico - Tecnólogo",
    degree: "Tecnólogo",
    mode: "Presencial",
  },
  {
    id: 21,
    name: "Direito",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 22,
    name: "Educação Física - Bacharelado e Licenciatura",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 23,
    name: "Educação Física - EaD",
    degree: "Bacharelado",
    mode: "Educação a Distância",
  },
  { id: 24, name: "Enfermagem", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 25,
    name: "Engenharia Ambiental e Sanitária",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 26,
    name: "Engenharia Civil",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 27,
    name: "Engenharia de Computação",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 28,
    name: "Engenharia de Produção",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 29,
    name: "Engenharia Elétrica",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 30,
    name: "Engenharia Mecânica",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 31,
    name: "Engenharia Química",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  { id: 32, name: "Estética", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 33,
    name: "Estética e Cosmética - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  { id: 34, name: "Farmácia", degree: "Bacharelado", mode: "Presencial" },
  { id: 35, name: "Fisioterapia", degree: "Bacharelado", mode: "Presencial" },
  { id: 36, name: "Fonoaudiologia", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 37,
    name: "Gastronomia",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 38,
    name: "Gestão Ambiental - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 39,
    name: "Gestão Comercial - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 40,
    name: "Gestão de Recursos Humanos - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 41,
    name: "Gestão Financeira - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 42,
    name: "Gestão Pública - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  { id: 43, name: "História", degree: "Licenciatura", mode: "Presencial" },
  {
    id: 44,
    name: "História - EaD",
    degree: "Licenciatura",
    mode: "Educação a Distância",
  },
  { id: 45, name: "Jornalismo", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 46,
    name: "Letras - EaD",
    degree: "Licenciatura",
    mode: "Educação a Distância",
  },
  {
    id: 47,
    name: "Logística - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 48,
    name: "Marketing - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  { id: 49, name: "Medicina", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 50,
    name: "Música - Bacharelado",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 51,
    name: "Música - Licenciatura",
    degree: "Licenciatura",
    mode: "Presencial",
  },
  {
    id: 52,
    name: "Nutrição",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 53,
    name: "Oceanografia",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  { id: 54, name: "Odontologia", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 55,
    name: "Pedagogia",
    degree: "Licenciatura",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 56,
    name: "Pedagogia Educação Infantil - EAD",
    degree: "Licenciatura",
    mode: "Educação a Distância",
  },
  {
    id: 57,
    name: "Pedagogia Para Anos Iniciais - EAD",
    degree: "Licenciatura",
    mode: "Educação a Distância",
  },
  {
    id: 58,
    name: "Processos Gerenciais - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  {
    id: 59,
    name: "Produção Audiovisual",
    degree: "Tecnólogo",
    mode: "Presencial",
  },
  { id: 60, name: "Psicologia", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 61,
    name: "Publicidade e Propaganda",
    degree: "Bacharelado",
    mode: "Presencial",
    special: "Dupla Titulação",
  },
  {
    id: 62,
    name: "Relações Internacionais",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 63,
    name: "Relações Públicas - EaD",
    degree: "Bacharelado",
    mode: "Educação a Distância",
  },
  {
    id: 64,
    name: "Secretariado Executivo",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 65,
    name: "Secretariado Executivo - EaD",
    degree: "Bacharelado",
    mode: "Educação a Distância",
  },
  {
    id: 66,
    name: "Segurança Pública - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
  },
  { id: 67, name: "Serviço Social", degree: "Bacharelado", mode: "Presencial" },
  {
    id: 68,
    name: "Serviço Social - EaD",
    degree: "Bacharelado",
    mode: "Educação a Distância",
  },
  {
    id: 69,
    name: "Sistemas de Informação",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 70,
    name: "Sistemas para Internet - EaD",
    degree: "Tecnólogo",
    mode: "Educação a Distância",
    disciplines: {
      "1º Período": [
        {
          name: "Algoritmos e Programação",
          credits: 4,
          workload: "60h",
          school: "NID Escola",
        },
        {
          name: "Criatividade e Inovação",
          credits: 4,
          workload: "60h",
          school: "NID Escola",
        },
        {
          name: "Educação Ambiental e Ética",
          credits: 4,
          workload: "60h",
          school: "NID Escola",
        },
        {
          name: "Startups Tecnológicas",
          credits: 4,
          workload: "60h",
          school: "NEI Escola",
        },
        {
          name: "Web Design",
          credits: 4,
          workload: "60h",
          school: "NEI Escola",
        },
      ],
      "2º Período": [
        {
          name: "Design de Interfaces",
          credits: 4,
          workload: "60h",
          school: "NEI Escola",
        },
        {
          name: "Programação Web",
          credits: 8,
          workload: "120h",
        },
        {
          name: "Banco de Dados",
          credits: 4,
          workload: "60h",
          school: "NEI Escola",
        },
        {
          name: "Sistemas Operacionais",
          credits: 4,
          workload: "60h",
          equivalence: "Ciência da Computação e Engenharia da Computação",
        },
      ],
    },
  },
  {
    id: 71,
    name: "Teatro - Bacharelado",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 72,
    name: "Teatro - Licenciatura",
    degree: "Licenciatura",
    mode: "Presencial",
  },
  {
    id: 73,
    name: "Turismo e Hotelaria",
    degree: "Bacharelado",
    mode: "Presencial",
  },
  {
    id: 74,
    name: "Turismo e Hotelaria - EaD",
    degree: "Bacharelado",
    mode: "Educação a Distância",
  },
  { id: 75, name: "Zootecnia", degree: "Bacharelado", mode: "Presencial" },
];

export const disciplines = {
  "1º Período": [
    {
      name: "Algoritmos e Programação",
      credits: 4,
      workload: "60h",
      school: "NID Escola",
    },
    {
      name: "Criatividade e Inovação",
      credits: 4,
      workload: "60h",
      school: "NID Escola",
    },
    {
      name: "Educação Ambiental e Ética",
      credits: 4,
      workload: "60h",
      school: "NID Escola",
    },
    {
      name: "Startups Tecnológicas",
      credits: 4,
      workload: "60h",
      school: "NEI Escola",
    },
    {
      name: "Web Design",
      credits: 4,
      workload: "60h",
      school: "NEI Escola",
    },
  ],
  "2º Período": [
    {
      name: "Design de Interfaces",
      credits: 4,
      workload: "60h",
      school: "NEI Escola",
    },
    {
      name: "Programação Web",
      credits: 8,
      workload: "120h",
    },
    {
      name: "Banco de Dados",
      credits: 4,
      workload: "60h",
      school: "NEI Escola",
    },
    {
      name: "Sistemas Operacionais",
      credits: 4,
      workload: "60h",
      equivalence: "Ciência da Computação e Engenharia da Computação",
    },
  ],
};
